import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex py-2 px-4 '>
          <div  className='flex gap-4 w-full'>
             <button  className='w-32 h-10  bg-black  rounded-s-none  ' >
                  <a href="/Alumini" className='text-red-600' >Alumini</a>
              </button>
             <button className='flex  border-2 w-72 h-10 py-2 '>
                <img  src="camera-video.png" className='w-5 h-5'/>
                <span className='text-xs  '>Participer au reunion d'information en ligne</span>
             </button>
          </div>
          <div className='flex  gap-10 px-12' >
            <a href=":#"><img src="facebook.png" className='w-8 h-8 '/></a>
            <a href=":#"><img src="twitter.png" className='w-8 h-8 '/></a>
            <a href=":#"><img src="in.png" className='w-8 h-8 '/></a>
          <div className=''>
            <a href=":#"><img src="traducteur.png" className='w-8 h-8  '/>
            <select className='w-2 h-2 pl-4  p'>
              <option value='text-xs'>FR</option>
              <option value='AG'>AG</option>
              <option value='FR'>FR</option>
            </select>
            </a>
          </div> 
          </div>
        </nav>
          

           <div class="bg-black w-full   border-2 flex justify-around  ">
	            <div class=" h-16 w-32 pb-24  ">
		              <img class="" src="Ecole241.jpg"></img>
	            </div>
               <div className='flex gap-8 pt-12 '>
   	                <a href=":#"><div class=" h-8 w-20  text-red-600 text-center">Accueil</div></a>
                    <a href=":#"><div class=" h-8 w-32 text-white text-center">Nos Formations</div></a>
                    <a href=":#"><div class=" h-8 w-32  text-white ">Nos campus</div></a>
                    <a href=":#"><div class=" h-8 w-44   text-white ">A propos de nous</div></a>
                     <a href="/Blog"><div class=" h-8 w-20  text-white ">Blog</div></a>
                    <a href="/Contacts"><div  className=" h-8 w-20  text-white ">Contacts </div></a>
                    <a href=":#"><div className=" h-8 w-44  text-red-600 border border-red-600">Postuler sur libreville</div></a>
                </div>
		        </div>
    {children}
        <footer className='w-full bg-black flex justify-around my-4 ' >
            <div className='w-32 h-24 '>
              <img src="Ecole241.jpg" className=' '/>
              <span className='text-xs text-white pb-8'>Plus qu’une formation , un metier</span>
            </div>
            <div className=' flex gap-24 py-12  '>
              <div className='w-28 h-16'>
                <span className=' text-white text-xs'>A propos de notre Contact Notre impact</span>
              </div>
              <div className='w-40 h-16'>
                <span className=' text-white text-xs'>Devenir formateur Devenir Partenaire</span>
              </div>
              <div className='w-44 h-16'>
                <span className=' text-white text-xs'>Formation référent Digital Formation Developpeur web</span>
              </div>
              <div className='w-44 h-16'>
                <span className=' text-white text-xs '>Campus de Libreville Campus de Port Gentil Campus de Moanda</span>
              </div>

            </div>
         </footer>




      </body>
    </html>
  )
}
